version: '3.9'

services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - './postgres-init:/docker-entrypoint-initdb.d'
      - 'postgres:/var/lib/postgresql/data'

volumes:
  postgres:
